spring.application.name=stranger-api-rest

spring.datasource.url=jdbc:postgresql://ep-still-morning-aipnu5ub-pooler.c-4.us-east-1.aws.neon.tech:5432/stranger?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_At2sWx4cYGgi
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true